### ISSUE TITLE
Change version to < 1.0.0 until project is activated

### ISSUE THREAD

**Issue by maoo** [symphonyoss/messageml-utils#1]
the `pom.xml` file shows that next released version will be `1.1`, however the project is not active yet and Foundation contribution guidelines expect incubating projects to use versions < 1.0.0.

More info on https://symphonyoss.atlassian.net/wiki/display/FM/Project+Lifecycle#ProjectLifecycle-IncubatingState

**Comment by ldrozdz** [comment]
Done, version set to 0.9.0.
