### ISSUE TITLE
Support for text translation of MessageML from context

### ISSUE THREAD

**Issue by ftbb** [symphonyoss/messageml-utils#13]
Would be nice to have a helper method to retrieve a text view from a given context.  

     String aBasicTextString = context.getText();

This would mean transforming mentions, cashtags, links etc into the respective text equivalents.

**Comment by ldrozdz** [comment]
Thanks for the suggestion! Is _context.getMarkdown()_ outputting too much or incorrect formatting? If absolutely plain text, without any formatting, is desirable, we can certainly add it.

**Comment by ldrozdz** [comment]
Fixed in 575937c885efb7aa74ad8f0dff7490b306e9b58c
